"use client";
import {useEffect,useState} from "react";
type Item={id:string;product_id:string|null;variant_id:string|null;quantity:number;unit_price:number;total:number;metadata:Record<string,unknown>};
type Order={id:string;customer_id:string|null;status:string;currency:string;subtotal:number;discount:number;total:number;payment_status:string;source_channel:string|null;created_at:string;updated_at:string;order_items:Item[]};
const statuses=["draft","pending","confirmed","fulfilled","canceled","failed"];
export default function OrderDetail({params}:{params:Promise<{id:string}>}){const[order,setOrder]=useState<Order|null>(null),[id,setId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{params.then(x=>setId(x.id))},[params]);useEffect(()=>{if(!id)return;fetch("/api/orders/"+id,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||"Unable to load order");setOrder(j.order)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load order")).finally(()=>setLoading(false))},[id]);
async function change(body:Record<string,string>){if(!id)return;setBusy(true);setError("");try{const r=await fetch("/api/orders/"+id,{method:"PATCH",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||"Action failed");setOrder(j.order)}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
if(loading)return <main className="workspace standalone"><p className="muted">Loading order…</p></main>;
if(error&&!order)return <main className="workspace standalone"><a className="muted" href="/orders">← Orders</a><div className="error-card">{error}</div></main>;
if(!order)return null;
const next=statuses.filter(s=>s!==order.status&&((order.status==="draft"&&["pending","canceled","failed"].includes(s))||(order.status==="pending"&&["confirmed","canceled","failed"].includes(s))||(order.status==="confirmed"&&["canceled","failed"].includes(s))||(order.status==="paid"&&["fulfilled","canceled","failed"].includes(s))));
return <main className="workspace standalone"><a className="muted" href="/orders">← Orders</a><div className="hero compact"><div className="eyebrow">Commerce / Order</div><h1>#{order.id.slice(0,8)}</h1><p>Created {new Date(order.created_at).toLocaleString()}</p></div>{error&&<div className="error-card">{error}</div>}<section className="card"><h2>Order state</h2><p><strong>Status:</strong> {order.status} · <strong>Payment:</strong> {order.payment_status}</p><p><strong>Customer:</strong> {order.customer_id??"Not linked"} · <strong>Channel:</strong> {order.source_channel??"—"}</p><div className="button-row">{next.map(s=><button key={s} disabled={busy} onClick={()=>change({status:s})}>{s}</button>)}</div></section><section className="card"><h2>Payment verification</h2><p className="muted">Recorded payment status: <strong>{order.payment_status}</strong>. This page cannot manually mark a payment as paid or refunded. Only a verified payment-provider workflow may change payment status.</p></section><section className="card"><h2>Items</h2><div className="table-scroll"><table><thead><tr><th>Product</th><th>Variant</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>{order.order_items.map(i=><tr key={i.id}><td>{i.product_id??"—"}</td><td>{i.variant_id??"—"}</td><td>{Number(i.quantity)}</td><td>{order.currency} {Number(i.unit_price).toLocaleString()}</td><td>{order.currency} {Number(i.total).toLocaleString()}</td></tr>)}</tbody></table></div><p><strong>Total: {order.currency} {Number(order.total).toLocaleString()}</strong></p></section></main>}
