import {NextResponse} from "next/server";
import {getTenantContext} from "@/lib/auth";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const statusMap:Record<string,number>={not_authorized:403,order_not_found:404,invalid_status:400,invalid_idempotency_key:400,invalid_status_transition:409};
const paymentMap:Record<string,number>={not_authorized:403,order_not_found:404,invalid_payment_status:400,invalid_idempotency_key:400,invalid_payment_transition:409};

function mapError(message:string,map:Record<string,number>,fallback:string){const k=Object.keys(map).find(x=>message.includes(x));return NextResponse.json({error:k??fallback},{status:k?map[k]:500});}
function key(req:Request){return req.headers.get("Idempotency-Key")?.trim()||"";}

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const {supabase,tenant}=await getTenantContext();if(!tenant)return NextResponse.json({error:"workspace_required"},{status:400});const {id}=await params;if(!UUID.test(id))return NextResponse.json({error:"invalid_order_id"},{status:400});const {data,error}=await supabase.from("orders").select("*,order_items(*)").eq("tenant_id",tenant.id).eq("id",id).maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"order_not_found"},{status:404});return NextResponse.json({order:data});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"order_read_failed"},{status:500});}}

export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const {supabase,tenant}=await getTenantContext();if(!tenant)return NextResponse.json({error:"workspace_required"},{status:400});const {id}=await params;if(!UUID.test(id))return NextResponse.json({error:"invalid_order_id"},{status:400});const body=await req.json();if(!body||typeof body!=="object")return NextResponse.json({error:"invalid_request"},{status:400});const k=key(req);if(k.length<8||k.length>200)return NextResponse.json({error:"invalid_idempotency_key"},{status:400});let data:any,error:any;if(typeof body.status==="string"){({data,error}=await supabase.rpc("transition_order_atomic",{p_tenant_id:tenant.id,p_order_id:id,p_new_status:body.status,p_idempotency_key:k}));if(error)return mapError(error.message||"",""+"" as any,"order_status_update_failed");}else if(typeof body.payment_status==="string"){({data,error}=await supabase.rpc("set_order_payment_atomic",{p_tenant_id:tenant.id,p_order_id:id,p_payment_status:body.payment_status,p_idempotency_key:k}));if(error){const msg=error.message||"";return mapError(msg,paymentMap,"order_payment_update_failed");}}else return NextResponse.json({error:"unsupported_order_action"},{status:400});const {data:order,error:readError}=await supabase.from("orders").select("*,order_items(*)").eq("tenant_id",tenant.id).eq("id",id).maybeSingle();if(readError)throw readError;if(!order)return NextResponse.json({error:"order_not_found"},{status:404});return NextResponse.json({order,result:data});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"order_action_failed"},{status:500});}}
