import{createClient}from"./supabase/server";
import type{SupabaseClient}from"@supabase/supabase-js";
export type Entitlements={status:string;plan:string;features:Record<string,unknown>;limits:Record<string,unknown>};
type Db=SupabaseClient;
export async function getEntitlements(tenantId:string,db?:Db):Promise<Entitlements>{const s=db??await createClient();const{data}=await s.from("subscriptions").select("status,ends_at,plans(code,features,limits)").eq("tenant_id",tenantId).maybeSingle();const p:any=data?.plans??{code:"trial",features:{},limits:{}};const expired=!!data?.ends_at&&new Date(data.ends_at).getTime()<Date.now();return{status:expired?"expired":data?.status??"trial",plan:p.code??"trial",features:p.features??{},limits:p.limits??{}}}
export function canUse(features:Record<string,unknown>,key:string){return features[key]===true}
export async function requirePlanActive(tenantId:string,db?:Db){const ent=await getEntitlements(tenantId,db);if(["expired","canceled","past_due","suspended"].includes(ent.status))throw new Error("plan_inactive");return ent}
export async function requireFeature(tenantId:string,key:string,db?:Db){const ent=await requirePlanActive(tenantId,db);if(!canUse(ent.features,key))throw new Error("feature_not_entitled");return ent}
export async function consumeUsage(tenantId:string,metric:string,quantity:number=1,db?:Db){if(!Number.isInteger(quantity)||quantity<1)throw new Error("invalid_usage_request");const ent=await requirePlanActive(tenantId,db);const raw=ent.limits[metric];const limit=typeof raw==="number"?raw:Number(raw);if(!Number.isFinite(limit)||limit<0)throw new Error("usage_limit_not_configured");const s=db??await createClient();const{data,error}=await s.rpc("consume_usage",{p_tenant_id:tenantId,p_metric:metric,p_quantity:quantity,p_limit:limit});if(error)throw new Error(error.message);const row=Array.isArray(data)?data[0]:data;if(!row?.allowed)throw new Error("usage_limit_exceeded");return{allowed:true,quantity:Number(row.quantity),limit}}
