"use client";
import {useEffect,useState} from "react";
type Product={id:string;sku:string|null;name:string;category:string|null;price:number|null;sale_price:number|null;inventory_quantity:number|null;availability:boolean|null};
type Variant={id:string;name:string;sku:string|null;price:number|null;sale_price:number|null;inventory_quantity:number|null;availability:boolean|null};
export default function Products(){
 const [products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState<Product|null>(null),[variants,setVariants]=useState<Variant[]>([]),[name,setName]=useState(""),[sku,setSku]=useState(""),[price,setPrice]=useState(""),[sale,setSale]=useState(""),[inventory,setInventory]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=async()=>{try{const r=await fetch("/api/products?limit=100",{cache:"no-store"}),j=await r.json();if(!r.ok)throw Error(j.error||"Unable to load products");setProducts(j.products??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load products")}};
 const loadVariants=async(id:string)=>{const r=await fetch("/api/product-variants?product_id="+encodeURIComponent(id),{cache:"no-store"}),j=await r.json();if(r.ok)setVariants(j.variants??[])};
 useEffect(()=>{load()},[]);
 const select=(p:Product)=>{setSelected(p);setName(p.name);setSku(p.sku??"");setPrice(p.price==null?"":String(p.price));setSale(p.sale_price==null?"":String(p.sale_price));setInventory(p.inventory_quantity==null?"":String(p.inventory_quantity));loadVariants(p.id)};
 const reset=()=>{setSelected(null);setVariants([]);setName("");setSku("");setPrice("");setSale("");setInventory("")};
 const save=async()=>{setSaving(true);setError("");try{const body={name,sku,price:price===""?null:Number(price),sale_price:sale===""?null:Number(sale),inventory_quantity:inventory===""?null:Number(inventory)};const r=await fetch("/api/products",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(selected?{...body,id:selected.id,reason:"Catalog workspace update"}:body)}),j=await r.json();if(!r.ok)throw Error(j.error||"Unable to save product");await load();select(j.product)}catch(e){setError(e instanceof Error?e.message:"Unable to save product")}finally{setSaving(false)}};
 return <main className="workspace standalone"><a className="muted" href="/dashboard">← Dashboard</a><div className="hero compact"><div className="eyebrow">Verified catalog</div><h1>Products</h1><p>Only approved catalog data is exposed to the sales workforce. Prices, stock and variants must come from tenant-owned records.</p></div>{error&&<div className="error-card">{error}</div>}<div className="customer-layout"><section className="card customer-list">{products.length===0?<div className="empty-card"><strong>No products yet</strong><p className="muted">Add the first verified product to the catalog.</p></div>:products.map(p=><button className={"customer-row "+(selected?.id===p.id?"selected":"")} key={p.id} onClick={()=>select(p)}><strong>{p.name}</strong><span>{p.sku||"No SKU"} · {p.category||"Uncategorized"}</span><small>{p.inventory_quantity==null?"Stock not recorded":String(p.inventory_quantity)+" in stock"}</small></button>)}</section><section className="card customer-detail"><div className="detail-head"><div><div className="eyebrow">{selected?"Edit product":"New product"}</div><h2>{selected?.name??"Add verified product"}</h2></div><button className="button secondary small" onClick={reset}>New</button></div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)} maxLength={120}/></label><label>Price (PKR)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Sale price (PKR)<input type="number" min="0" step="0.01" value={sale} onChange={e=>setSale(e.target.value)}/></label><label>Inventory<input type="number" min="0" step="1" value={inventory} onChange={e=>setInventory(e.target.value)}/></label></div><div className="detail-head"><span className="muted">Tenant-scoped and audited.</span><button className="button" onClick={save} disabled={saving||!name.trim()}>{saving?"Saving…":selected?"Save changes":"Add product"}</button></div>{selected&&<div className="section"><div className="section-head"><div><div className="eyebrow">Product options</div><h3>Variants</h3></div><span className="muted">{variants.length} recorded</span></div>{variants.length===0?<p className="muted">No variants recorded yet.</p>:variants.map(v=><div className="step" key={v.id}><strong>{v.name}</strong><span>{v.sku||"No SKU"} · {v.inventory_quantity??"Stock not recorded"}</span></div>)}</div>}</section></div></main>}